name: Build Release

on:
  push:
    tags:
      v\d+\.\d+\.\d+

jobs:
  tagged-release:

    runs-on:
      ubuntu-latest

    steps:
      - name: "Getting the sources"
        uses: actions/checkout@v2

      - name: "Build"
        run: |
          echo "a" > a.txt
          echo "b" > b.txt
          echo "${GITHUB_REF#refs/tags/}"

      - name: "Build Package"
        run: zip ${GITHUB_REF#refs/tags/}.zip *.txt

      - name: "Check"
        run: ls -l

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.zip
