name: Add tag

on: push

jobs:
  add_tag:

    runs-on: ubuntu-latest

    steps:
      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: v0.1.1
          message: Release for version v0.1.1
          token: ${{ secrets.GITHUB_TOKEN }}
