name: Add tag

on: push

jobs:
  get_package_version:

    runs-on: ubuntu-latest

    steps:
      - name: "Getting the sources"
        uses: actions/checkout@v2

      - name: "Set up the NPM environment"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dplocki'

      - name: "Get version of last NPM package"
        id: GetLastPackageVersion
        run: echo "::set-output name=version::"`npm info @dplocki/generic-conversation-bot version`
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: "Get version from package.json"
        id: GetCurrentVersion
        run: echo "::set-output name=version::"`node -p 'require("./examples/package.json").version'`

      - name: "Compering version"
        run: |
          CURRENT_VERSION=${{ steps.GetCurrentVersion.outputs.version }}
          LATEST_PACKAGE=${{ steps.GetLastPackageVersion.outputs.version }}

          echo $CURRENT_VERSION $LATEST_PACKAGE

          if [ "$CURRENT_VERSION" = "$LATEST_PACKAGE" ]; then
              echo "No changes in package"
          else
              echo "Strings are not equal."
          fi

      - name: Create Tag
        uses: negz/create-tag@v1
        with:
          version: v${{ steps.GetCurrentVersion.outputs.version }}
          message: Release for version v${{ steps.GetCurrentVersion.outputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
