name: Add tag

on: push

jobs:
  add_tag:

    runs-on: ubuntu-latest

    steps:
      - name: Git Tag Action
        uses: hole19/git-tag-action@v1.0
        env:
          TAG: v.${ "0.0.1"}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
