name: "Test of publish"

on:
  push:
    branches:
      master
    tags:
      releases/[1-9]+.[0-9]+.[0-9]+

jobs:
  build_release:

    runs-on:
      ubuntu-latest

    steps:
      - name: "Getting the sources"
        uses: actions/checkout@v2

      - name: "Build"
        run: |
          mkdir build
          echo "${GITHUB_REF:19}" > build/v.txt

      - name: "Publish"
        uses: actions/upload-artifact@v2
        with:
          name: congenial-broccoli-${{ GITHUB_REF:19 }}.zip
          path: ./build
