name: Build Release

on:
  push:
    tags:
      v\d+\.\d+\.\d+

jobs:
  tagged-release:

    runs-on:
      ubuntu-latest

    steps:
      - name: "Getting the sources"
        uses: actions/checkout@v2

      - name: "Build"
        run: |
          echo "a" > a.txt
          echo "b" > b.txt

      - uses: montudor/action-zip@v0.1.1
        with:
          args: zip -qq -r "${GITHUB_REF:19}.zip" *.txt

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            *.zip
