name: Display the repo files

on: push

jobs:
  display message:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Show me the files
        run: ls -l
