name: Checking version

on: push

jobs:
  get_package_version:

    runs-on: ubuntu-latest

    steps:
      - name: "Getting the sources"
        uses: actions/checkout@v2

      - name: "Set up the NPM"
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dplocki'

      - name: "Compering version"
        run: |
          CURRENT_VERSION=`node -p 'require("./examples/package.json").version'`
          LATEST_PACKAGE=`npm info @dplocki/generic-conversation-bot version`

          echo $CURRENT_VERSION $LATEST_PACKAGE

          if [ "$CURRENT_VERSION" = "$LATEST_PACKAGE" ]; then
              echo "No changes in package"
          else
              echo "Strings are not equal."
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
