name: Checking version

on: push

jobs:
  get_package_version:

    runs-on: ubuntu-latest

    steps:
      - name: "Getting the sources"
        uses: actions/checkout@v2

      - name: "Set up the NPM"
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: "Compering version"
        run: |
          CURRENT_VERSION=`node -p 'require("./examples/package.json").version'`
          LATEST_PACKAGE=`npm info @dplocki/generic-conversation-bot version`

          echo $CURRENT_VERSION $LATEST_PACKAGE

          if [ "$CURRENT_VERSION" = "$LATEST_PACKAGE" ]; then
              echo "Strings are equal."
          else
              echo "Strings are not equal."
          fi
